### PR TITLE
Command API

### PR DESCRIPTION
**Pull request by stachu540**
This is simplify command API. Estaminate work time 45 minutes. I guess you will use it well. Right?

### CODE REVIEW

**Comment by ghostzero** [comment]
It would be cool if you could give an example of how to register a command. Currently there is no command with this new api.

**Comment by stachu540** [comment]
```java
Set<Command> commands = new LinkedHashSet()
commands.put(new SystemCommand()) // this is a example

CommandBootstrapper bootstrapper = new CommandBootstrapper("<prefix>", new CommandListener(), commands)
// register commands extends Command can be added in initialization as the last arguments Collection<Command>

bootstrapper.registerCommand(HelpCommand()) //same way like a aboved

client.getDispatcher().registerListener(bootstrapper)
// bootstrapper is extends IListener<MessageReceivedEvent> soo you can add him directly to the dispatcher
```

**Comment by TheCricket** [comment]
I'm still not sure about this tbh, i'd like some more opinions

**Comment by stachu540** [comment]
More options u said? Here is `CustomCommand` with bulder. Also you can customize your own `CommandListener` just like [my way](https://github.com/GlitchLib/bot-butler/tree/master/src/main/kotlin/glitch/commands/discord/api) - Builded in Koltin, check those files.

**Comment by TheCricket** [comment]
No no opinions, thoughts. I wanted to hear more feedback from the community lol

**Comment by stachu540** [comment]
Go for it. Have it more questions... sure. Just name it.

**Pull request closed without merging**
